# -*- coding: utf-8 -*-
"""answerkey_alternative_Homework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I8NPaL1PpJ_7IbQmsbvvFOfV8iENaYta

## <div align = "center">Homework 2</div>

## <div align = "center">Python</div>

###### Welcome to Homework 2. In this homework you will be using techniques you learned throughout Week 2. The purpose of this homework is to ensure you've mastered the basics of Python. Feel free to refer to the cheatsheet while working through these problems

### Grading

##### Every question in this homework is worth 2 points. There are a total of 10 questions.

In order to work on the questions and submit them for grading, you'll need to run the code block beloW. It will ask for your student ID number and then create a folder that will house your answers for each question. At the very end of the notebook, there is a code section that will download this folder as a zip file to your computer. This zip file will be your final submission.
"""

import os
import shutil

!rm -rf sample_data

student_id = input('Please Enter your Student ID: ') # Enter Student ID.

while len(student_id) != 9:
 student_id = int('Please Enter your Student ID: ')  
  
folder_location = f'{student_id}/Week_Two/Homework' # Week  Two -> Homework
if not os.path.exists(folder_location):
  os.makedirs(folder_location)
  print('Successfully Created Directory, Lets get started')
else:
  print('Directory Already Exists')

"""## Python Questions

### Q1

Use a combination of the string methods you have learned to write a block of code that would take the string "computer" and change it to "CoMPute"
"""

# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/1.py
# Please note that if you uncomment and press multiple times, the program will keep appending to the file.
# So only uncomment it when you want to save your answer.

string = "computer"
new_string = string[0].upper()+string[1]+string[2].upper()+string[3].upper()+string[4:7]
print(new_string)

"""### Q2

Write a simple program that, depending on the given age, returns the price of a movie ticket. 
 For ages 12 and under, it is free.
Ages 13 to 65 pay 15 dollars, and ages 66 and older pay 10 dollars.
"""

# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/1.py
# Please note that if you uncomment and press multiple times, the program will keep appending to the file.
# So only uncomment it when you want to save your answer.
age = 20
fare =0
if age <13:
  fare = 0
elif age >= 13 and age<66:
  fare = 15
else:
  fare = 10

print(fare)

"""### Q3

The following is a grocery shopping list. ['Candy', 'apple', 'avocados', 'strawberry'] perform the following tasks using the list functions you have learned so far.

1.  Add the item "Orange" to the list.
2.  Remove "apple" from the list.
3. Add grapes and banana to a separate list, and add that list to your original shopping list.
"""

# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/1.py
# Please note that if you uncomment and press multiple times, the program will keep appending to the file.
# So only uncomment it when you want to save your answer.
my_list = ['Candy', 'apple', 'avocados', 'strawberry'] 
my_list.append('Orange')
my_list.remove('apple')
new_list = ['grapes','banana']
my_list.append(new_list)
print(my_list)

"""### Q4

For each of the following tasks, determine which data structure (list, tuples, or dictionaries) is the best.

1. You want to store the names of your favorite movies, and over time you may want to add new favorite movies to this collection.
2. You want to keep track of student names and their student IDs in a class. It is important to know which ID belongs to whom.
3. You have finalized a list of textbooks you need to purchase for this semester, and you are certain no additional books are needed.
"""

# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/1.py
# Please note that if you uncomment and press multiple times, the program will keep appending to the file.
# So only uncomment it when you want to save your answer.

# 1. list because you can edit lists in Python.
# 2. Dictionary, since it is a good idea to map their names to their student IDs.
#3. tuples, since tuples cannot be editted and our list is finalized.

"""### Q5

You have been given a list of candies. However, you want to find out how many KitKats there are on the list. How can you count the number of KitKats using a while loop? 
An example list: [KitKat, Snickers, KitKat, Hershey’s, Toblerone]
"""

# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/1.py
# Please note that if you uncomment and press multiple times, the program will keep appending to the file.
# So only uncomment it when you want to save your answer.

list = ["KitKat", "Snickers", "KitKat", "Hershey’s", "Toblerone"]
i = 0
count = 0
while (i<len(list)-1):
  if list[i]=="KitKat":
    count +=1
  i +=1
print(count)

"""### Q6

The following dictionary maps each student to their favorite classes. 
Students = {'Mark': ['Chemistry', 'Sociology'], 'Emma': ['Physics', 'Mathematics'], 'Jerry': ['English', 'psychology', 'History']}
1. Print Emma's favorite classes.
2. Replace English with Statistics, in Jerry's list of favorite classes. 
3. Add "Sara" to the dictionary and put Biology in her list of favorite classes.
"""

# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/1.py
# Please note that if you uncomment and press multiple times, the program will keep appending to the file.
# So only uncomment it when you want to save your answer.
students = {'Mark': ['Chemistry', 'Sociology'], 'Emma': ['Physics', 'Mathematics'], 'Jerry': ['English', 'psychology', 'History']}
print(students["Emma"])
students['Jerry'].remove('English')
students['Jerry'].append('Statistics')
students["Sara"] = ["Biology"]
print(students)

"""### Q7

Look up another common data structure (like lists, dictionaries, and tuples) and briefly explain how data is organized in it.
"""

# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/9.txt
# Please note that if you uncomment and press multiple times, the program will keep appending to the file.
# So only uncomment it when you want to save your answer.

'(example answer) Sets are another type of data that hold several values in python. However, they are different from a list such that sets are not ordered and you cannot index into a set.'

"""### Q8

Create a tuple with a length of your choice but put only values of 0 and 1 in it. Using a tuple method to count how many of each there is in the tuple, print the difference between the number of zeros and ones.
"""

# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/9.txt
# Please note that if you uncomment and press multiple times, the program will keep appending to the file.
# So only uncomment it when you want to save your answer.
my_tuple = (0,0,1,0,1)
zeros = my_tuple.count(0)
ones = my_tuple.count(1)
if ones == zeros:
  print(0)
elif ones > zeros:
  print(ones - zeros)
else:
  print(zeros - ones)

"""### Q9

Given a length n of a list, print out what the largest index in that list can be. Hint: think about the largest index in a list of 3 items, and look for a pattern.
"""

# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/9.txt
# Please note that if you uncomment and press multiple times, the program will keep appending to the file.
# So only uncomment it when you want to save your answer.
list = [1,2,3,4,5]
n = len(list)
largest = n-1
print(largest)

"""### Q10

Explain what a function in python is, and come up with an example where writing a function can be useful, and outline the function parameters.
"""

# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/10a.txt
# Please note that if you uncomment and press multiple times, the program will keep appending to the file.
# So only uncomment it when you want to save your answer.

'example correct answer (other answers that imply a similar concept are correct as well.'
'Functions are blocks of code that perform a certain task within a program. they may or may not receive parameters. It should be noted that
'if you define variables in a function, they are only recognized within the function (they are local variables) not outside the function.
'This is their syntax in python: def function_name(parameter1,parameter2)'
'If you need to use a function, you should call it using this notation: function_name(parameter1, parameter2)
'
'There are several advantages to using function. For instance, a function makes debugging easier, and breaks down a complex program into smaller,
'more managable tasks. An example of when a function can be useful: Assume we want to write a program for accounting purposes. It is much 
'easier to use a function that calculates the salary of each employee, as opposed to having to write the same block of code over and over.
'also, if there is a problem with how we calculate the income, it is easier to point it out and debug it.'